=== Paul-Wallstone/TeachMeSkillsRepo/src/HW10_2021_05_14/xmlandjson/medicalclinic2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="inttype">
        <xs:restriction base="xs:positiveInteger"/>
    </xs:simpleType>

    <xs:simpleType name="stringtype">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="stufftype">
        <xs:sequence>
            <xs:element type="stringtype" name="name"/>
            <xs:element type="stringtype" name="position"/>
            <xs:element type="stringtype" name="department"/>
            <xs:element type="inttype" name="experience"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="clinictype">
        <xs:sequence>
            <xs:element name="stuff" type="stufftype" maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="clinic" type="clinictype"/>
</xs:schema>

=== Paul-Wallstone/TeachMeSkillsRepo/src/HW10_2021_05_14/xmlandjson/medicalclinic.xml
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE clinic [
        <!ELEMENT clinic (stuff)*>
        <!ELEMENT stuff (fio,position,department,experience)>
        <!ELEMENT fio (#PCDATA)>
        <!ELEMENT position (#PCDATA)>
        <!ELEMENT department (#PCDATA)>
        <!ELEMENT experience (#PCDATA)>
        ]>

<clinic xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="medicalclinic2.xsd">
    <stuff>
        <name>Gregory House</name>
        <position>Head of department</position>
        <department>Diagnostic medicine</department>
        <experience>27</experience>
    </stuff>
    <stuff>
        <name>Robert Chase</name>
        <position>Doctor</position>
        <department>Diagnostic medicine</department>
        <experience>10</experience>
    </stuff>
    <stuff>
        <name>James Wilson</name>
        <position>Head of department</position>
        <department>Cancer diagnostic</department>
        <experience>23</experience>
    </stuff>
    <stuff>
        <name>Allison Cameron</name>
        <position>Doctor</position>
        <department>Diagnostic medicine</department>
        <experience>12</experience>
    </stuff>
</clinic>
